openapi: 3.0.0
info:
  title: Content API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Get list of books
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{book_id}/modules:
    get:
      summary: Get list of modules for a book
      parameters:
        - in: path
          name: book_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the book
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
  /modules/{module_id}/chapters:
    get:
      summary: Get list of chapters for a module
      parameters:
        - in: path
          name: module_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the module
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChapterSummary'
  /chapters/{chapter_id}:
    get:
      summary: Get a specific chapter's content
      parameters:
        - in: path
          name: chapter_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the chapter
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
    Module:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        book_id:
          type: string
          format: uuid
    ChapterSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        module_id:
          type: string
          format: uuid
    Chapter:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        module_id:
          type: string
          format: uuid
        textual_content:
          type: string
        learning_objectives:
          type: array
          items:
            type: string
        real_world_examples:
          type: array
          items:
            type: object # Simplified, can be more detailed
        ros_gazebo_isaac_references:
          type: array
          items:
            type: object # Simplified, can be more detailed
        practical_exercises:
          type: array
          items:
            type: object # Simplified, can be more detailed
        metadata:
          type: object # Simplified, can be more detailed
