openapi: 3.0.0
info:
  title: Personalization API
  version: 1.0.0
paths:
  /chapters/{chapter_id}/personalize:
    post:
      summary: Request personalized chapter content
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: chapter_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the chapter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_background_context: # Or derive from user token
                  type: object
                  properties:
                    software_background:
                      type: string
                    hardware_robotics_background:
                      type: string
      responses:
        '200':
          description: Personalized chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalizedChapter'
        '401':
          description: Unauthorized
        '404':
          description: Chapter not found
components:
  schemas:
    PersonalizedChapter:
      type: object
      properties:
        chapter_id:
          type: string
          format: uuid
        title:
          type: string
        personalized_content:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
