# backend/src/services/ai_agent.py

from typing import Optional
from backend.src.services.rag_service import RAGService
from backend.src.models.content import Query, ConversationalAIResponse

class AIAgentService:
    def __init__(self, rag_service: RAGService):
        self.rag_service = rag_service

    async def process_user_query(self, user_query_text: str, user_id: Optional[str] = None, 
                                 context_type: str = "entire_book", context_reference: Optional[str] = None) -> ConversationalAIResponse:
        """
        Processes a user query by first formulating it, sending it to the RAG service,
        and then returning the conversational AI response.
        """
        # Create a Query object from the input parameters
        # For simplicity, timestamp is generated here, in a real app it might be passed or generated by a middleware
        import datetime
        query_timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
        
        query = Query(
            user_id=user_id,
            query_text=user_query_text,
            context_type=context_type,
            context_reference=context_reference,
            timestamp=query_timestamp
        )
        
        # Delegate to RAG service for processing
        response = await self.rag_service.process_query(query)
        return response

# Initialize RAGService and then AIAgentService
rag_service_instance = RAGService()
ai_agent_service = AIAgentService(rag_service=rag_service_instance)
